[project]
name = "cfd-hemodynamic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cadquery>=2.6.1",
    "lxml>=6.0.2",
    "numpy>=2.2.6",
]
